---
- name: Preconfiguration
  hosts: all
  become: true
  roles:
    - role: docker
      tags: docker

    - role: preconfig
      tags: preconfig

    - role: deploy
      tags: deploy

    # - role: user
    #   tags: user

    # - role: portainer
    #   tags: portainer
